### PR TITLE
Check routing table size in HLC/LLC switching

### PR DESCRIPTION
**Pull request by jfim**
Check the size of the routing tables when switching between high
level consumer and low level consumer routing tables.

### CODE REVIEW

**Comment by mcvsubbu** [comment]
lgtm

can u pls update the unit tests to reflect this? thanks

**Comment by mcvsubbu** [comment]
Also, if you can please take out the commented lines. I meant to take them out, but missed them somehow. thanks.

**Comment by mcvsubbu** [comment]
Pleas disregard my comment about unit tests. There is a TODO to re-factor this class anyway, and we will get the unit test coverage at that time.

**Comment by jfim** [comment]
Okay, I'll merge this as is, we can take out the comments when we refactor this class anyway.

**Pull request merged**
