### PR TITLE
Fix incorrect LLC partitionRange extraction

### PR DESCRIPTION
**Pull request by jfim**
Fix the extraction of partitionRange for the low level consumer.
Update unit test.

### CODE REVIEW

**Comment by fx19880617** [comment]
LGTM

**Comment by mcvsubbu** [comment]
Can we not have partition ranges in the segment name please?

**Comment by mcvsubbu** [comment]
lgtm

**Comment by jfim** [comment]
Discarding this PR as it is obsoleted by #216 and #219.

**Pull request closed without merging**
