### PR TITLE
Renaming StarTree v1/v2 to on-heap/off-heap.

### PR DESCRIPTION
**Pull request by mayankshriv**
1. Renamed StarTreeV2 to StarTreeOffHeap. StarTree(V1) cannot be renamed
as it will break backward compatibility (Java de-serialization requires
class name to be same).

2. Renamed StarTreeIndexNodeV2 to StarTreeIndexNodeOffHeap.

3. Renamed StarTreeV1ToV2Converter to StarTreeOnHeapToOffHeapConverter.

4. Renamed all references to v1 or v2 (for star tree) in
variables/members/method names.

### CODE REVIEW

**Comment by kishoreg** [comment]
thanks for fixing this right away. Out of curiosity, if we clone StarTreeV1 class to StarTreeHeap and change StarTreeV1 to extend StarTreeHeap would it have worked. we dont have to do this but just know if this was possible. Anyhow bottom line is never use java serialization even if its initial implementation

**Comment by kishoreg** [comment]
LGTM

**Comment by kishoreg** [comment]
lgtm

**Comment by mayankshriv** [comment]
Not sure if the suggested work-around for the Java serialization issue and see if it works. Will need to investigate.

**Pull request merged**
