### PR TITLE
Allow configurable log2m to be passed to FastHllAggregationFunction

### PR DESCRIPTION
**Pull request by antumbde**
Refactor aggregation operators to pass segment metadata to use the
configured log2m value in segmentMetadata during aggregation

### CODE REVIEW

**Comment by antumbde** [comment]
@kishoreg : I considered that. The information has to flow down to AggregationFunctionFactory through multiple layers. Adding specific parameters will bloat up the interface with different parameters at all levels. This will also add switch statements in all these methods for aggregation function to decide which parameters to pass since parameters are aggregation function dependent.
The right approach is for planner to set up these operators instead of executors but that's a bigger surgery.

Let's discuss this tomorrow.

**Comment by kishoreg** [comment]
@mayankshriv Can you also look into this. Adwait has valid points, I will also spend some time looking into the code. Let's figure out a way to avoid passing segmentMetadata.

**Comment by antumbde** [comment]
Updated PR to add AggregationOperatorConfig that can be instantiated with specific fields. This isolates bottom layers from segmentmetadata . (SegmentMetadata is NOT retained inside AggregationOperatorConfig).

BAsically, another layer of indirection

**Comment by Jackie-Jiang** [comment]
IMO, passing segment metadata is fine since we might need segment information to perform aggregations in different ways. If we really want a layer of abstraction, maybe AggregationMetadata is a better name?

**Comment by antumbde** [comment]
check https://github.com/linkedin/pinot/pull/871. That addresses this
concern

**Comment by antumbde** [comment]
Discarding this PR in favor of #871

**Pull request closed without merging**
