### PR TITLE
Adding way to construct old segment upload endpoint

### PR DESCRIPTION
**Pull request by jenniferdai**
* We want a migration path from the old segment endpoint to the new one. Adding the method back to use the old segment endpoint. Also added a new method to use the call the new endpoint.
* Changed all references in open source to use the new endpoint as well.

### CODE REVIEW

**Comment by jenniferdai** [comment]
@fx19880617

**Comment by jenniferdai** [comment]
@Jackie-Jiang I think it may be nice to help users construct the request (in case other people wanted to migrate as well), thoughts? Maybe I can rename my new one

**Comment by Jackie-Jiang** [comment]
@jenniferdai I would rather rename the old one instead, because the whole code base uses the new one.

**Comment by jenniferdai** [comment]
@Jackie-Jiang makes sense, how about this most recent approach?

**Comment by Jackie-Jiang** [comment]
@jenniferdai We should keep the new one as default. We can bring back the old one with name like **getDeprecatedUploadSegmentHttpURI()**. @fx19880617 Any thoughts?

**Comment by fx19880617** [comment]
> @jenniferdai We should keep the new one as default. We can bring back the old one with name like **getDeprecatedUploadSegmentHttpURI()**. @fx19880617 Any thoughts?

I think my major concern is that if people blindly upgrade both server and client. Then segment URI push will still fail since v2 api on controller is not backward compatible with v1 api. 

I'm open to change my code to use the old api, however not sure if this will break other users.

**Pull request merged**
