### PR TITLE
Handle BOOLEAN type in FieldSpec

### PR DESCRIPTION
**Pull request by jfim**

### CODE REVIEW

**Comment by Jackie-Jiang** [comment]
We also need to add it to getDefaultNullValue()

**Comment by jfim** [comment]
There's no default null value for booleans, it needs to be specified explicitly. When it is specified explicitly, the actual value is returned, so there is no change in behavior in `getDefaultNullValue()`.

**Comment by Jackie-Jiang** [comment]
LGTM.

**Comment by Jackie-Jiang** [comment]
One problem is that when people do not set a default null value for boolean but try to get one, it will throw exception. I think false might be a good "default" default null value for boolean?

**Comment by jfim** [comment]
We had a long discussion about this and there's no real good default value for booleans. If for example `Integer.MIN_VALUE` is a bad value for your application, you can filter it out, but if "false" doesn't work with your application, there's no way to remove these values once they're ingested. It's better at this point to not ingest data than cause problems later on.

**Comment by Jackie-Jiang** [comment]
Make sense, LGTM.

**Pull request merged**
