### PR TITLE
Removed dependency on javax.ws.rs in favor of explicitly setting response content type

### PR DESCRIPTION
**Pull request by antumbde**

### CODE REVIEW

**Comment by mayankshriv** [comment]
Don't you need to remove the dependency from the pom file as well?

**Comment by jfim** [comment]
LGTM. We should clean up all the API responses since half of them return JSONObject.toString() and the other half return strings, but that's out of scope for this.

**Comment by antumbde** [comment]
Removed from pom

**Comment by mayankshriv** [comment]
lgtm

**Pull request merged**
