### PR TITLE
Added server api to read segment metadata

### PR DESCRIPTION
**Pull request by antumbde**

### CODE REVIEW

**Comment by rven1** [comment]
Changes look good.

**Comment by antumbde** [comment]
Realtimesegments also use the same SegmentMetadataImpl class right ?  So, there shouldn't be a difference

**Comment by mcvsubbu** [comment]
realtime segments subclass SegmentMetadataImpl, and some methods are overridden to throw exception. So, adding a test will future-proof this.

**Comment by mcvsubbu** [comment]
I stand corrected, this is not an inherited class. Go for it.

**Pull request merged**
